[package]
name = "example"
version = "0.1.0"
authors = ["maik klein <maikklein@googlemail.com>"]

[dependencies]

enumflags2 = {path = "../enumflags"}
enumflags2_derive = {path = "../enumflags_derive"}
