[package]
name = "enumflags2_derive"
version = "0.5.0"
authors = ["maik klein <maikklein@googlemail.com>", "Jakub \"NieDżejkob\" Kądziołka <kuba@kadziolka.net"]
description = "Enum-based bitflags - the macros"
license = "MIT"
repository = "https://github.com/NieDzejkob/enumflags2"
keywords = ["enum", "bitflag", "flag", "bitflags"]

[dependencies]
syn = {version = "^0.15", features = ["extra-traits"]}
quote = "^0.6"
proc-macro2 = "^0.4"

[lib]
proc-macro = true

[features]
default = []
nostd = []
