name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rust: [nightly, stable, 1.34.2]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        default: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      if: matrix.rust == 'nightly'
      run: cargo clippy -- -D warnings
